[package]
name = "dbgen"
version = "0.1.1"
authors = ["kennytm <kennytm@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Generate random test cases for databases"
repository = "https://github.com/kennytm/dbgen"


[dependencies]
structopt = "0.2"
pest = "2.0"
pest_derive = "2.0"
failure = "0.1"
rand = "0.5"
data-encoding = "2.1"
regex-syntax = "0.6"
pbr = "1.0"
num-traits = "0.2"
rayon = "1.0"
zipf = "4.0.1"
chrono = { version = "0.4", default-features = false }
ryu = "0.2"
pcg_rand = "=0.9.1" # FIXME: unpin the version until robojeb/pcg_rand#9 is fixed
xoshiro = "0.0.4"
serde_derive = "1.0"
serde = "1.0"
muldiv = "0.2"

[dev-dependencies]
regex = "1.0"
tempfile = "3.0"
serde_json = "1.0"
diff = "0.1"

[features]
nightly = ["rand/nightly"]

[profile.release]
panic = "abort"
